eleicao_adm_proposta:
    resource: "@EleicaoAdmBundle/Resources/config/routing/proposta.yml"
    prefix:   /proposta

eleicao_adm_candidato:
    resource: "@EleicaoAdmBundle/Resources/config/routing/candidato.yml"
    prefix:   /candidato

eleicao_adm_partido:
    resource: "@EleicaoAdmBundle/Resources/config/routing/partido.yml"
    prefix:   /partido

eleicao_adm_homepage:
    path:     /
    defaults: { _controller: EleicaoAdmBundle:Default:index }