site_votacao:
    path:     /
    defaults: { _controller: EleicaoSiteBundle:Votacao:index }

site_votacao_votar:
    path:     /votar
    defaults: { _controller: EleicaoSiteBundle:Votacao:votar }

site_votacao_efetuar_voto:
    path:     /{id}/efetuarVoto
    defaults: { _controller: EleicaoSiteBundle:Votacao:efetuarVoto }